# -*- coding: utf-8 -*-
# -*- mode: org -*-
#+startup: beamer overview indent
#+LANGUAGE: pt-br
#+TAGS: noexport(n)
#+EXPORT_EXCLUDE_TAGS: noexport
#+EXPORT_SELECT_TAGS: export

#+Title: Algoritmos
#+Subtitle: *INF01202*
#+Author: Prof. Lucas Mello Schnorr
#+Date: \copyleft

#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [xcolor=dvipsnames]
#+OPTIONS: title:nil H:1 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+LATEX_HEADER: \input{org-babel.tex}

#+latex: \newcommand{\mytitle}{Comando Condicional (if)}
#+latex: \mytitleslide

* Sumário

- Comando condicional =if=
  - Com um único comando
- Exemplos
  1. Ler valor, emitir mensagem se menor que 10
  2. Processar uma venda de livros em uma livraria
  3. Localização de um ponto no plano

#+latex: \vfill\pause

- Comando condicional =if=
  - Com múltiplos comandos
- Exemplos
  1. Processar uma venda de livros, com desconto

#+latex: \vfill\pause

- Cuidados nos erros comuns

* Motivação para comandos de seleção condicional

#+latex: \cortesia{../../../Algoritmos/Edison/Teoricas/aula04_slide_21.pdf}{Prof. Edison Pignaton de Freitas}

* Comandos de seleção condicional

#+latex: \cortesia{../../../Algoritmos/Edison/Teoricas/aula04_slide_22.pdf}{Prof. Edison Pignaton de Freitas}

* Comando =if= (condicional simples, com único comando)

#+latex: \cortesia{../../../Algoritmos/Mara/Teoricas/Aula04-If_else_slide_22.pdf}{Prof. Mara Abel}

* Exemplo #1 - Enunciado, Algoritmo

Ler um valor e, no caso de ser menor do que 10, emitir uma mensagem

#+BEGIN_SRC C :tangle e/exemplo-if-1.c
/* Enunciado:
   Ler um valor e, no caso de ser menor do que 10, emitir uma mensagem */

/* Algoritmo:
1. Início
2. Ler Valor
3. Se Valor < 10
3.1 Escrever mensagem
4. Fim */

#include <stdio.h>
int main() {
  int valor;
  printf("Valor 1:\n");
  scanf("%d", &valor);
  if (valor < 10)
    printf("%d é menor que 10.\n", valor);
  return 0;
}
#+END_SRC

* Exemplo #2 - Enunciado, Algoritmo

Processar uma venda de livros em uma livraria. Obter código do tipo de
livro vendido (A, B, C) e número de unidades, calcular e informar
valor a pagar. Valores por tipo: A (R$10,00); B (R$20,00); C
(R$30,00). Caso tenham sido vendidos mais de 10 livros, emitir uma
mensagem.

#+latex: \vfill\pause

#+BEGIN_EXPORT latex
\setbeamertemplate{itemize/enumerate body begin}{\scriptsize}
\setbeamertemplate{itemize/enumerate subbody begin}{\tiny}
#+END_EXPORT

#+latex: {\scriptsize
Algoritmo ProcessaUmaVenda

{ processa uma venda e avisa caso tenham sido vendidas mais de 10 unidades }

entradas: codigo {do tipo do livro};
          quantidade {de livros vendidos}

saídas: total (valor total a ser pago);
        mensagem (caso mais de 10 unidades vendidas)

#+latex: \pause

1. Início
2. Ler código e quantidade
3. Se código for A
   1. total = quantidade * 10;
4. Se código for B
   1. total = quantidade * 20;
5. Se código for C
   1. total = quantidade * 30;
6. Escrever total
7. Se quantidade maior que 10
   1. Escrever "mais de 10 livros vendidos"
8. Fim.
#+latex: }

* Exemplo #2 (Código em C)

#+BEGIN_SRC C :tangle e/exemplo-livros.c
/* processa uma venda e avisa caso se mais de 10
unidades vendidas foram vendidas */
#include<stdio.h>
int main(void)
{
  char codigo;
  int quantidade;
  float total;
  printf("digite o codigo do produto e número de unidades:\n");
  scanf(" %c %d", &codigo, &quantidade);
  if (codigo == 'a' || codigo == 'A')
    total = quantidade * 10;
  if (codigo == 'b' || codigo == 'B')
    total = quantidade * 20;
  if (codigo == 'c' || codigo == 'C')
    total = quantidade * 30;
  printf("o valor a pagar é de R$ %6.2f.\n",total);
  if (quantidade > 10)
    printf("Foram vendidas mais de 10 unidades do tipo %c.\n", codigo);
  return 0;
}
#+END_SRC

#+begin_src shell :results output :dir e
gcc exemplo-livros.c -o exemplo-livros
#./exemplo-livros
#+end_src

#+RESULTS:

* Exemplo #3 (Enunciado)

#+latex: \cortesia{../../../Algoritmos/Mara/Teoricas/Aula04-If_else_slide_27.pdf}{Prof. Mara Abel}

* Exemplo #3 (Entendendo o Enunciado)

#+latex: \cortesia{../../../Algoritmos/Edison/Teoricas/aula04_slide_35.pdf}{Prof. Edison Pignaton de Freitas}

* Exemplo #3 (Pensamento Computacional \to Passos)

#+latex: \cortesia{../../../Algoritmos/Mara/Teoricas/Aula04-If_else_slide_29.pdf}{Prof. Mara Abel}

* Exemplo #3 (Algoritmo)

#+BEGIN_EXPORT latex
\setbeamertemplate{itemize/enumerate body begin}{\scriptsize}
\setbeamertemplate{itemize/enumerate subbody begin}{\tiny}
#+END_EXPORT

#+latex: {\scriptsize
Algoritmo LocalizaQuadrante

Entradas: x, y (coordenadas)

Saída: mensagem (localização)

#+latex: \pause

1. Início
2. Ler x e y
3. Se x for 0 e y for 0
   1. Escrever "ponto na origem" @@latex: \pause@@
4. Se x maior que 0 e y maior que 0
   1. Escrever "quadrante 1"
5. Se x menor que 0 e y maior que 0
   1. Escrever "quadrante 2"
6. Se x menor que 0 e y menor que 0
   1. Escrever "quadrante 3"
7. Se x maior que 0 e y menor que 0
   1. Escrever "quadrante 4"  @@latex: \pause@@
8. Se x diferente de 0 e y igual a 0
   1. Escrever "eixo dos x"
9. Se x igual a 0 e y diferente de 0
   1. Escrever "eixo dos y"
10. Fim
#+latex: }

* Exemplo #3 (Código em C)

#+BEGIN_SRC C :tangle e/exemplo-coordenadas.c
/* Obtem coordenadas e informa localização */
#include <stdio.h>
int main() {
  float x, y; //Entrada
  printf("Coordenadas: x = ");
  scanf("%f", &x);
  printf("e y = ");
  scanf("%f", &y);
  if (x == 0 && y == 0)
    printf("Ponto na origem");
  if (x > 0 && y > 0)
    printf("Ponto no quadrante 1.\n");
  if (x < 0 && y > 0)
    printf("Ponto no quadrante 2.\n");
  if (x < 0 && y < 0)
    printf("Ponto no quadrante 3.\n");
  if (x > 0 && y < 0)
    printf("Ponto no quadrante 4.\n");
  if (x != 0 && y == 0)
    printf("Ponto no eixo dos x.\n");
  if (x == 0 && y != 0)
    printf("Ponto no eixo dos y.\n");
  return 0;
}
#+END_SRC

#+begin_src shell :results output :dir e
gcc exemplo-coordenadas.c -o exemplo-coordenadas
./exemplo-coordenadas
#+end_src

#+RESULTS:
: 
:  Coordenadas: x = e y = 
:  Ponto na origem
* Comando =if= (cond. composto, com múltiplos comandos)

#+latex: \cortesia{../../../Algoritmos/Edison/Teoricas/aula04_slide_33.pdf}{Prof. Edison Pignaton de Freitas}

* Exemplo #4 (Livros, com desconto)

Processar uma venda de livros em uma livraria. Obter código do tipo de
livro vendido (A, B, C) e número de unidades, calcular e informar
valor a pagar. Valores por tipo: A (R$10,00); B (R$20,00); C
(R$30,00). *Se o livro for do Tipo A, dar 10% de desconto.* Caso
tenham sido vendidos mais de 10 livros, emitir uma mensagem.

#+latex: \vfill\pause

#+BEGIN_EXPORT latex
\setbeamertemplate{itemize/enumerate body begin}{\scriptsize}
\setbeamertemplate{itemize/enumerate subbody begin}{\tiny}
#+END_EXPORT

#+latex: {\scriptsize
Algoritmo ProcessaUmaVenda

{ processa uma venda e avisa caso tenham sido vendidas mais de 10 unidades }

entradas: codigo {do tipo do livro};
          quantidade {de livros vendidos}

saídas: total (valor total a ser pago);
        mensagem (caso mais de 10 unidades vendidas)

#+latex: \pause

1. Início
2. Ler código e quantidade
3. Se código for A
   1. total = quantidade * 10;
   2. total = total * 0.9; // desconto de 10%!
4. Se código for B
   1. total = quantidade * 20;
5. Se código for C
   1. total = quantidade * 30;
6. Escrever total
7. Se quantidade maior que 10
   1. Escrever "mais de 10 livros vendidos"
8. Fim.
#+latex: }

* Exemplo #4 (Código em C)

#+BEGIN_SRC C :tangle e/exemplo-livros-desconto.c
/* processa uma venda e avisa caso se mais de 10
unidades vendidas foram vendidas */
#include<stdio.h>
int main(void)
{
  char codigo;
  int quantidade;
  float total;
  printf("digite o codigo do produto e número de unidades:\n");
  scanf(" %c %d", &codigo, &quantidade);
  if (codigo == 'a' || codigo == 'A') {
    total = quantidade * 10;
    total = total * 0.90;
  }
  if (codigo == 'b' || codigo == 'B')
    total = quantidade*20;
  if (codigo == 'c' || codigo == 'C')
    total = quantidade*30;
  printf("o valor a pagar é de R$ %6.2f.\n",total);
  if (quantidade > 10)
    printf("Foram vendidas mais de 10 unidades do tipo %c.\n", codigo);
  return 0;
}
#+END_SRC


#+begin_src shell :results output :dir e
gcc exemplo-livros-desconto.c -o exemplo-livros-desconto
#./exemplo-livros-desconto
#+end_src

* Cuidados nos erros comuns

- Confundir atribuição com comparação igual
  #+BEGIN_SRC C
  if (codigo = 'b'|| codigo == 'B')
    total = quantidade*20;  
  #+END_SRC

#+latex: \pause

- Esquecer as chaves em comando ~if~ com múltiplos comandos dentro
  #+BEGIN_SRC C
  //...
  if (codigo == 'a'|| codigo == 'A')
    total = quantidade * 10;
    total = total * 0.90;
  if (codigo == 'b'|| codigo == 'B')
    total = quantidade*20;
  //...
  #+END_SRC
