# -*- coding: utf-8 -*-
# -*- mode: org -*-
#+startup: beamer overview indent
#+LANGUAGE: pt-br
#+TAGS: noexport(n)
#+EXPORT_EXCLUDE_TAGS: noexport
#+EXPORT_SELECT_TAGS: export

#+Title: Algoritmos
#+Subtitle: *INF01202*
#+Author: Prof. Lucas Mello Schnorr
#+Date: \copyleft

#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [xcolor=dvipsnames]
#+OPTIONS: title:nil H:1 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+LATEX_HEADER: \input{org-babel.tex}

#+latex: \newcommand{\mytitle}{Comando de seleção =switch-case=}
#+latex: \mytitleslide

* Configuração                                                     :noexport:

#+BEGIN_SRC emacs-lisp
(setq org-latex-listings 'minted
      org-latex-packages-alist '(("" "minted"))
      org-latex-pdf-process
      '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
        "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))
(setq org-latex-minted-options
       '(("frame" "lines")
         ("fontsize" "\\scriptsize")))
#+END_SRC

#+RESULTS:
| frame    | lines       |
| fontsize | \scriptsize |
* Aula de hoje

#+latex: \cortesia{../../../Algoritmos/Edison/Teoricas/aula06_slide_12.pdf}{Prof. Edison Pignaton de Freitas}

* Sumário

- Motivação para =switch-case= com exemplos =if-else=
- Funcionamento do =switch-case=

* Relembrando o fluxograma do =if=...

#+latex: \cortesia{../../../Algoritmos/Mara/Teoricas/Aula06-Switch_slide_02.pdf}{Prof. Mara Abel}

* ... e do =if-else=

#+latex: \cortesia{../../../Algoritmos/Mara/Teoricas/Aula06-Switch_slide_03.pdf}{Prof. Mara Abel}

* Dado um problema

#+latex: \cortesia{../../../Algoritmos/Mara/Teoricas/Aula06-Switch_slide_04.pdf}{Prof. Mara Abel}

* Possível solução usando apenas =if...=

#+latex: \cortesia{../../../Algoritmos/Claudio/Teorica/Aula06-if_ANINHADO_e_switch_slide_12.pdf}{Prof. Claudio Jung}

* ...ou com =if-else=

Uma solução mais eficiente.

#+latex: \cortesia{../../../Algoritmos/Claudio/Teorica/Aula06-if_ANINHADO_e_switch_slide_13.pdf}{Prof. Claudio Jung}

* Uma terceira solução

Veja em [[./a06-mensagem.c]], uma solução ineficiente.

#+begin_src C :tangle e/a06-mensagem.c
/* Imprime uma mensagem, de acordo com um código lido - solução usando if simples
   Entrada: valor (inteiro) lido do teclado; Saida: Mensagem na tela */
#include <stdio.h>
int main ( )
{
  int cod;
  printf("Codigo (1 a 4): ");
  scanf ("%d", &cod);
  if (cod == 1)
    printf ("\nMensagem 1\n");
  else if (cod == 2)
    printf ("\nMensagem 2\n");
  else if (cod == 3)
    printf ("\nMensagem 3\n");
  else if (cod == 4)
    printf ("\nMensagem 4\n");
  else if (cod < 1 || cod > 4)
    printf ("\nMensagem de erro\n");
  return 0;
}
#+end_src

Como fica o *fluxograma*?

* Fluxograma do exemplo

#+latex: \cortesia{../../../Algoritmos/Mara/Teoricas/Aula06-Switch_slide_07.pdf}{Prof. Mara Abel}

* Apresentação do =switch-case=

#+latex: \cortesia{../../../Algoritmos/Edison/Teoricas/aula06_slide_13.pdf}{Prof. Edison Pignaton de Freitas}

* Detalhamento do comando =switch-case=
  
#+latex: \cortesia{../../../Algoritmos/Edison/Teoricas/aula06_slide_14.pdf}{Prof. Edison Pignaton de Freitas}

* Emprego de =switch-case= para o programa da mensagem

Veja em [[./a06-mensagem-switch-case_v1.c]].

Vamos testar!

#+BEGIN_SRC C :tangle e/a06-mensagem-switch-case_v1.c
#include <stdio.h>
int main () {
  int cod;
  printf("Codigo (1 a 4): ");
  scanf ("%d", &cod);
  switch (cod) {
  case 1:
    printf ("Mensagem 1.\n");
  case 2:
    printf ("Mensagem 2.\n");
  case 3:
    printf ("Mensagem 3.\n");
  case 4:
    printf ("Mensagem 4.\n");
  default:
    printf ("Mensagem de erro.\n");
  }
  return 0;
}
#+END_SRC

* Fluxograma do funcionamento do exemplo anterior

#+latex: \cortesia{../../../Algoritmos/Claudio/Teorica/Aula06-if_ANINHADO_e_switch_slide_16.pdf}{Prof. Claudio Jung}

* Comando de quebra (=break=) dentro do =switch-case=

#+latex: \cortesia{../../../Algoritmos/Claudio/Teorica/Aula06-if_ANINHADO_e_switch_slide_19.pdf}{Prof. Claudio Jung}

* Exemplo de uso de =break= no =switch-case=

Veja em [[./a06-mensagem-switch-case_v2.c]].

#+BEGIN_SRC C :tangle e/a06-mensagem-switch-case_v2.c
#include <stdio.h>
int main () {
  int cod;
  printf("Codigo (1 a 4): ");
  scanf ("%d", &cod);
  switch (cod) {
  case 1:
    printf ("Mensagem 1.\n");
    break;
  case 2:
    printf ("Mensagem 2.\n");
    break;
  case 3:
    printf ("Mensagem 3.\n");
    break;
  case 4:
    printf ("Mensagem 4.\n");
    break;
  default:
    printf ("Mensagem de erro.\n");
    break;
  }
  return 0;
}
#+END_SRC

* Fluxograma do funcionamento com =break=

#+latex: \cortesia{../../../Algoritmos/Claudio/Teorica/Aula06-if_ANINHADO_e_switch_slide_20.pdf}{Prof. Claudio Jung}

