#+TITLE: Lista 02
#+startup: overview indent

Lista de exercícios de programas com estrutura sequencial que são
enriquecidos com estruturas condicionais (=if=, =if-else=, =if-else
if-else=, etc).

* Detecta múltiplos

Faça um programa que lê dois valores inteiros n1 e n2 e
verifica se n1 é múltiplo de n2. Caso seja múltiplo, o programa
deve exibir uma mensagem informando isso.

#+begin_src C :tangle lista02_detecta_multiplos.c
#include <stdio.h>

int main() {
    //Variáveis de entrada
    int n1, n2;
    //Variável auxiliar
    int lidos;
    //Variável de saída
    int multiplo;

    //entrada de dados
    printf("Insira os valores inteiros de n1 e n2: ");
    lidos = scanf("%d%d", &n1, &n2);
    if (lidos != 2) {
        printf("Houve um erro ao ler os valores!\n");
        return 1;
    }

    //Verificação se é múltiplo
    multiplo = n1 % n2 == 0;

    //Saída de dados
    if (multiplo == 1){
      printf("O valor %d eh multiplo de %d.\n", n1, n2);
    }
    return 0;
}

#+end_src

* Calcula diferença

Escrever um programa para ler dois valores numéricos e apresentar a
diferença do maior pelo menor.

#+begin_src C :tangle lista02_calcula_diferenca.c
#include <stdio.h>

int main() {
    
    //Variáveis de entrada
    float n1, n2;
    //Variáveis auxiliares
    int lidos;
    //Variáveis de saída
    float resultado;

    //Entrada de dados
    printf("Insira o valor dos números: ");
    lidos = scanf("%f %f", &n1, &n2);
    if (lidos != 2) {
        printf(Houve erro na leitura dos valores!\n);
        return 1;
    }

    //Saída de dados
    if (n1 > n2)
        printf("O valor da diferença de n1 por n2 eh %.2f\n", n1 - n2);
    else 
        printf("O valor da diferença de n2 por n1 eh %.2f\n", n2 - n1);


    return 0;
}

#+end_src


* Peso ideal

Tendo como dados de entrada a altura e o sexo (M ou F) de uma pessoa,
construa um programa para calcular seu peso ideal, utilizando as
seguintes fórmulas:

• Para Homens: ( 72.7 * altura ) - 58;
• Para Mulheres: ( 62.1 * altura) - 44.7.

#+begin_src C :tangle lista02_peso_ideal.c
#include <stdio.h>

int main() {
    
    //Variáveis de entrada
    float altura;
    char sexo;
    //Variáveis auxiliares
    int lidos;
    //Variáveis de saída
    float peso_ideal;

    //Entrada de dados
    printf("Insira a altura: ");
    lidos = scanf("%f", &altura);
    if (lidos != 1) {
        printf("Houve erro na leitura!\n");
        return 1;
    }

    printf("Insira on sexo (M ou F): ");
    lidos = scanf(" %c", &sexo);            //Espaço na frente pelo buffer do teclado
    if (lidos != 1) {
        printf("Houve erro na leitura!\n");
        return 1;
    } else if (sexo != 'M' && sexo != 'F') {
        printf("Sexo inserido eh invalido!\n");
        return 1;
    }

    //Processamento 
    if (sexo == 'M') 
        peso_ideal = 72.7 * altura - 58;
    else 
        peso_ideal = 62.1 * altura - 44.7;
    

    //Saída de dados
    printf("O peso ideal eh %.2f\n", peso_ideal);

    return 0;
}

#+end_src

* Classifica triângulo

Faça um programa em C que lê 3 lados de um triângulo e escreve na tela
se ele é um triângulo isósceles (2 lados com medidas iguais e 1
diferente), escaleno (3 lados com medidas diferentes) ou equilátero (3
lados com medidas iguais).

#+begin_src C :tangle lista02_classifica_triangulo.c
#include <stdio.h>

int main() {
    
    //Variáveis de entrada
    float a, b, c;
    //Variáveis auxiliares
    int lidos;


    //Entrada de dados
    printf("Insira os valores dos lados: ");
    lidos = scanf("%f %f %f", &a, &b, &c);
    if (lidos != 3) {
        printf("Houve erro na leitura!\n");
        return 1;
    }

    //Saída de dados
    if (a == b && b == c) printf("O triangulo eh equilatero!\n");
    else if (a == b || b == c || a == c) printf("O triangulo eh isosceles!\n");
    else printf("O triangulo eh escaleno!\n");

    return 0;
}

#+end_src

* Altura abaixo da média

Faça um programa em C que lê a altura de 3 pessoas, calcula a média da
altura dessas 3 pessoas e escreva quantas pessoas tem estatura abaixo
da média.

#+begin_src C :tangle lista02_altura_abaixo_da_media.c
#include <stdio.h>

int main() {
    
    //Variáveis de entrada
    float p1, p2, p3;
    //Variáveis auxiliares
    int lidos;
    float media;
    //Variáveis de saída
    int abaixo = 0;


    //Entrada de dados
    printf("Insira os valores das alturas: ");
    lidos = scanf("%f %f %f", &p1, &p2, &p3);
    if (lidos != 3) {
        printf("Houve erro na leitura!\n");
        return 1;
    }

    //Processamento 
    media = (p1 + p2 + p3) / 3;

    if (p1 < media) abaixo++;
    if (p2 < media) abaixo++;
    if (p3 < media) abaixo++;

    //Saída de dados
    if (abaixo == 0) printf("Nenhuma pessoa esta abaixo da media!\n");
    else printf("Temos %d pessoas abaixo da media!\n", abaixo);

    return 0;
}

#+end_src

* Saldo bancário

Faça um programa em C que lê o código de cliente (um número) e o saldo
bancário de 3 clientes de um banco. O programa deve calcular a média
do saldo bancário desses clientes, e deve informar o código dos
clientes cujo saldo seja superior à média.

#+begin_src C :tangle lista02_saldo_bancario.c
#include <stdio.h>

int main() {
    
    //Variáveis de entrada
    int c1, c2, c3;
    float s1, s2, s3;
    //Variáveis auxiliares
    int lidos, acima = 0;
    float media;

    //Entrada de dados
    //Cliente 1
    printf("Insira o id do cliente: ");
    lidos = scanf("%d", &c1);
    if (lidos != 1) {
        printf("Houve erro na leitura!\n");
        return 1;
    }

    printf("Insira o saldo do cliente: ");
    lidos = scanf("%f", &s1);
    if (lidos != 1) {
        printf("Houve erro na leitura!\n");
        return 1;
    }

    //Cliente 2
    printf("Insira o id do cliente: ");
    lidos = scanf("%d", &c2);
    if (lidos != 1) {
        printf("Houve erro na leitura!\n");
        return 1;
    }

    printf("Insira o saldo do cliente: ");
    lidos = scanf("%f", &s2);
    if (lidos != 1) {
        printf("Houve erro na leitura!\n");
        return 1;
    }

    //Cliente 3
    printf("Insira o id do cliente: ");
    lidos = scanf("%d", &c3);
    if (lidos != 1) {
        printf("Houve erro na leitura!\n");
        return 1;
    }

    printf("Insira o saldo do cliente: ");
    lidos = scanf("%f", &s3);
    if (lidos != 1) {
        printf("Houve erro na leitura!\n");
        return 1;
    }
    

    //Processamento 
    media = (s1 + s2 + s3) / 3;

    //Saída de dados
    if (s1 > media) {
        printf("O cliente %d esta acima da media!\n", c1);
        acima++;
    }
    if (s2 > media) {
        printf("O cliente %d esta acima da media!\n", c2);
        acima++;
    }
    if (s3 > media) {
        printf("O cliente %d esta acima da media!\n", c3);
        acima++;
    }
    
    //Se nenhum ficou acima, mete uma mensagem tb
    if (acima == 0) printf("Nao houve clientes com saldo acima da media!\n");

    return 0;
}

#+end_src 

* Cotação do dólar

Faça um programa em C que lê o a cotação do dólar de 3 dias. Se não
houve variação na cotação, o programa deve informar que não houve
variação.

#+begin_src C :tangle lista02_cotacao_do_dolar.c
#include <stdio.h>

int main() {
    
    //Variáveis de entrada
    float c1, c2, c3;
    //Variáveis auxiliares
    int lidos;

    //Entrada de dados
    printf("Insira as cotacoes do dolar: ");
    lidos = scanf("%f %f %f", &c1, &c2, &c3);
    if (lidos != 3) {
        printf("Houve erro na leitura!\n");
        return 1;
    }

    //Saída de dados
    if (c1 == c2 && c2 == c3) printf("Nao houve variacao na cotacao!\n");
    else printf("Houve variacao na cotacao!\n");

    return 0;
}

#+end_src

* Preço de produtos

Faça um programa em C que lê o preço unitário de 3 produtos comprados
por um cliente hipotético e um determinado valor de referência. O
programa deve:
- Calcular o preço médio dos produtos.
- Se o valor de referência for menor que a média, o programa deve
  determinar quais dos valores são inferiores ao valor de referência.
- Se a média for inferior ao valor de referência, o programa deve
  determinar quais dos valores são inferiores à média.

  #+begin_src C :tangle lista02_preco_de_produtos.c
  #include <stdio.h>

int main() {
    
    //Variáveis de entrada
    float v1, v2, v3, ref;
    //Variáveis auxiliares
    int lidos, aux = 0;
    float media;

    //Entrada de dados
    printf("Insira os valores dos produtos comprados: ");
    lidos = scanf("%f %f %f", &v1, &v2, &v3);
    if (lidos != 3) {
        printf("Houve erro na leitura!\n");
        return 1;
    }

    printf("Insira o valor de referencia: ");
    lidos = scanf("%f", &ref);
    if (lidos != 1) {
        printf("Houve erro na leitura!\n");
        return 1;
    }

    //Processamento
    media = (v1 + v2 + v3) / 3;

    //Saída de dados
    printf("Valor medio dos produtos: %.2f\n", media);
    if (ref < media) {
        //Determinar quais valores são inferiores ao de referência
        if (v1 < ref) {
            aux++;
            printf("O valor 1 eh inferior ao de referencia\n");
        }
        if (v2 < ref) {
            aux++;
            printf("O valor 2 eh inferior ao de referencia\n");
        }
        if (v3 < ref) {
            aux++;
            printf("O valor 3 eh inferior ao de referencia\n");
        }

        if (aux == 0) printf("Nenhum valor foi inferior ao de referencia\n");
    } else {
        //Determinar os valores que são inferiores a media
        if (v1 < media) {
            aux++;
            printf("O valor 1 eh inferior ao da media\n");
        }
        if (v2 < media) {
            aux++;
            printf("O valor 2 eh inferior ao da media\n");
        }
        if (v3 < media) {
            aux++;
            printf("O valor 3 eh inferior ao da media\n");
        }

        if (aux == 0) printf("Nenhum valor eh inferior ao da media\n");
    }
    return 0;
}

#+end_src

* Resistência

Faça um programa que auxilie no cálculo da resistência (em ohm),
diferença de potencial (em volt) e corrente elétrica (em ampére). O
programa deve exibir uma mensagem perguntando ao usuário qual das
grandezas ele quer calcular, relacionando a cada opção um valor
numérico: 1-Resistência, 2-Diferença de potencial e 3-Corrente
elétrica.

Dependendo da opção selecionada, o programa deve ler o valor das duas
grandezas necessárias para calcular o que se deseja e deve exibir o
resultado. Por exemplo, se a opção for 1, indicando que o programa
deve calcular a resistência, o programa deve ler a diferença de
potencial e a corrente elétrica e exibir o resultado.

#+begin_src C :tangle lista02_resistencia.c
#include <stdio.h>

int main() {
    
    //Variáveis de entrada
    float r, v, i;
    int escolha;
    //Variáveis auxiliares
    int lidos;

    //Entrada de dados
    printf("Escolha o que deseja calcular\n1.Resistencia\n2.Diferença de potencial\n3.Corrente eletrica\n");
    lidos = scanf("%d", &escolha);
    if (lidos != 1) {
        printf("Houve um erro na leitura!\n");
        return 1;
    }

    //Processamento e saída
    switch (escolha) { //Simula os if else encadeados, mas assim facilita legibilidade
        case 1:
            printf("Insira a diferença de potencial e a corrente respectivamente: ");
            lidos = scanf("%f %f", &v, &i);
            if (lidos != 2) {
                printf("Houve erro na leitura!\n");
                return 1;
            }

            r = v / i;
            printf("A resistencia eh de %.2f ohms\n", r);
            break;

        case 2:
            printf("Insira a resistencia e a corrente respectivamente: ");
            lidos = scanf("%f %f", &r, &i);
            if (lidos != 2) {
                printf("Houve erro na leitura!\n");
                return 1;
            }

            v = r * i;
            printf("A diferença de potencial eh de %.2f volts\n", v);
            break;

        case 3:
            printf("Insira a diferença de potencial e a resistencia respectivamente: ");
            lidos = scanf("%f %f", &v, &r);
            if (lidos != 2) {
                printf("Houve erro na leitura!\n");
                return 1;
            }

            i = v / r;
            printf("A corrente eh de %.2f amperes\n", i);
            break;

        default:
            printf("Escolha inválida\n");
    }
    
    return 0;
}

#+end_src

* Detecção de triângulo

Escrever um programa que lê 3 valores a, b, c e verifica se eles
formam ou não um triângulo. Caso os valores formam um triângulo,
calcular e escrever a área deste triângulo. Para que 3 lados formem um
triângulo, eles devem satisfazer às seguintes condições:

- | b - c | < a < b + c 
- | a - c | < b < a + c 
- | a - b | < c < a + b

Ou seja, cada lado deve ser maior que o valor absoluto da diferença
entre os outros dois e deve ser menor que a soma dos outros dois. Se
algum dos lados não satisfaz este requisito, então os 3 lados não
podem formar um triângulo.

#+begin_src C :tangle lista02_deteccao_de_triangulo.c
#include <stdio.h>
#include <math.h>

int main() {
    
    //Variáveis de entrada
    float a, b, c;
    //Variáveis auxiliares
    int lidos;

    //Entrada de dados 
    printf("Entre com os valores dos lados: ");
    lidos = scanf("%f %f %f", &a, &b, &c);
    if (lidos != 3) {
        printf("Houve um erro na leitura!\n");
        return 1;
    }

    //Processamento e saída de dados
    if (fabs(b - c) < a && a < b + c &&
        fabs(a - c) < b && b < a + c &&
        fabs(a - b) < c && c < a + b) {
            printf("Os lados inseridos podem formar um triângulo!\n");
    } else {
        printf("Os lados nao correspondem a um triangulo!\n");
    }
    
    return 0;
}

#+end_src

* Calcula módulo

Escrever um programa para efetuar a leitura de um valor inteiro
positivo ou negativo e apresentar o número lido como sendo um valor
positivo, ou seja, o programa deverá apresentar o módulo de um número
fornecido. Não utilize funções da biblioteca math.h.

#+begin_src C :tangle lista02_calcula_modulo.c
#include <stdio.h>

int main() {
    
    //Variáveis de entrada
    int n;
    //Variáveis auxiliares
    int lidos;

    //Entrada de dados 
    printf("Entre com o valor: ");
    lidos = scanf("%d", &n);
    if (lidos != 1) {
        printf("Houve um erro na leitura!\n");
        return 1;
    }

    //Processamento e saída de dados
    if (n < 0) printf("O valor absoluto de %d eh %d\n", n, -n);
    else printf("O valor absoluto de %d eh %d\n", n, n);
    
    return 0;
}

#+end_src

* Descobre pares

Escrever um programa para efetuar a leitura de 3 números e apresentar
os números que são pares.

#+begin_src C :tangle lista02_descobre_pares.c
#include <stdio.h>

int main() {
    
    //Variáveis de entrada
    int n1, n2, n3;
    //Variáveis auxiliares
    int lidos, pares = 0;

    //Entrada de dados 
    printf("Entre com os valores: ");
    lidos = scanf("%d %d %d", &n1, &n2, &n3);
    if (lidos != 3) {
        printf("Houve um erro na leitura!\n");
        return 1;
    }

    //Processamento e saída de dados
    if (n1 % 2 == 0) {
        printf("O numero %d eh par\n", n1);
        pares++;
    }
    if (n2 % 2 == 0) {
        printf("O numero %d eh par\n", n2);
        pares++;
    }
    if (n3 % 2 == 0) {
        printf("O numero %d eh par\n", n3);
        pares++;
    }

    if (pares == 0) printf("Nao houve nenhum numero par!\n");
    
    return 0;
}

#+end_src

* Loja de descontos

Uma loja fornece 5% de desconto para funcionários e 10% de desconto
para clientes especiais. Faça um programa que calcule o valor total a
ser pago por uma pessoa. O programa deverá ler o valor total da compra
efetuada e um código numérico que identifique se o comprador é um
cliente comum (1) ou um funcionário (código 2) ou cliente especial
(código 3).

#+begin_src C :tangle lista02_loja_de_descontos.c
#include <stdio.h>

int main() {
    
    //Variáveis de entrada
    int id;
    float compra;
    //Variáveis auxiliares
    int lidos;

    //Entrada de dados 
    printf("Entre com o valor da compra: ");
    lidos = scanf("%f", &compra);
    if (lidos != 1) {
        printf("Houve um erro na leitura!\n");
        return 1;
    }
    printf("Entre com o id do cliente: ");
    lidos = scanf("%d", &id);
    if (lidos != 1) {
        printf("Houve um erro na leitura!\n");
        return 1;
    }

    //Processamento e saída de dados
    if (id == 1) printf("O valor da compra eh de R$%.2f\n", compra);    
    else if (id == 2) printf("O valor da compra eh de R$%.2f\n", compra * .95);    
    else if (id == 3) printf("O valor da compra eh de R$%.2f\n", compra * .9);    
    else printf("ID invalido!\n");

    return 0;
}

#+end_src

* Distância cartesiana

Escrever um programa que lê um conjunto de 6 valores: X1, X2, Y1, Y2,
Z1, Z2, que representam as coordenadas cartesianas de 3 pontos: P1(X1,
X2), P2(Y1, Y2), P3(Z1, Z2). Calcule a distância entre P1 e P2, P1 e
P3, P2 e P3.

#+begin_example
d(P1,P2) = sqrt((x1-x2)^2 + (y1-y2)^2)
#+end_example

Se os segmentos de reta formam um triângulo, calcular e escrever a
área deste triângulo.

#+begin_src C :tangle lista02_distancia_cartesiana.c
#include <stdio.h>
#include <math.h>

int main() {
    
    //Variáveis de entrada
    float x1, x2, y1, y2, z1, z2, distxy, distxz, distyz, area;
    //Variáveis auxiliares
    int lidos;

    //Entrada de dados 
    printf("Entre com as coordenadas do ponto 1: ");
    lidos = scanf("%f %f", &x1, &x2);
    if (lidos != 2) {
        printf("Houve um erro na leitura!\n");
        return 1;
    }
    printf("Entre com as coordenadas do ponto 2: ");
    lidos = scanf("%f %f", &y1, &y2);
    if (lidos != 2) {
        printf("Houve um erro na leitura!\n");
        return 1;
    }
    printf("Entre com as coordenadas do ponto 3: ");
    lidos = scanf("%f %f", &z1, &z2);
    if (lidos != 2) {
        printf("Houve um erro na leitura!\n");
        return 1;
    }
   

    //Processamento de dados
    distxy = sqrt(pow(x1 - y1, 2) + pow(x2 - y2, 2));
    distxz = sqrt(pow(x1 - z1, 2) + pow(x2 - z2, 2));
    distyz = sqrt(pow(z1 - y1, 2) + pow(z2 - y2, 2));

    //Saída de dados
    printf("dist(p1, p2) = %.2f\ndist(p1, p3) = %.2f\ndist(p2, p3) = %.2f\n", distxy, distxz, distyz);

    if (fabs(distxy - distxz) < distyz && distyz < distxy + distxz &&
        fabs(distxz - distyz) < distxy && distxy < distxz + distyz &&
        fabs(distxy - distyz) < distxz && distxz < distxy + distyz) {

            /*
            Se formar um triângulo, calcularemos a área usando a regra de que a área eh a metade do modulo do determinante da matriz
            |x1 x2 1 |
            |y1 y2 1 |
            |z1 z2 1 |
            */
            area = .5 * fabs(x1 * y2 + y1 * z2 + x2 * z1 - z1 * y2 - y1 * x2 - z2 * x1); 
            printf("Os segmentos formam um triângulo de área %.2f\n", area);

    } else {
        printf("Os segmentos de reta nao formam um triangulo!\n");
    }
    return 0;
}

#+end_src

* Categorização de nadador

Elabore um programa que, dada a idade de um nadador, classifique-o em
uma das seguintes categorias:

- Infantil A: 5 a 7 anos;
- Infantil B: 8 a 10 anos;
- Juvenil A: 11 a 13 anos;
- Juvenil B: 14 a 17 anos;
- Sênior: maiores de 18 anos.

#+begin_src C :tangle lista02_categorizacao_de_nadador.c
#include <stdio.h>

int main() {
    
    //Variáveis de entrada
    int idade;
    //Variáveis auxiliares 
    int lidos;

    //Entrada de dados
    printf("Entre com a idade do individuo: ");
    lidos = scanf("%d", &idade);
    if (lidos != 1) {
        printf("Houve um erro na leitura!\n");
        return 1;
    }

    //Processamento e saída de dados
    if (idade < 5) printf("Maninho eh novo demais pra se classificar!\n");
    else if (idade <= 7) printf("Esta na categoria Infantil A\n");
    else if (idade <= 10) printf("Esta na categoria Infantil B\n");
    else if (idade <= 13) printf("Esta na categoria Juvenil A\n");
    else if (idade <= 17) printf("Esta na categoria Juvenil B\n");
    else printf("Esta na categoria Senior\n");

    return 0;
}

#+end_src

* Tipo de média

Um usuário deseja um algoritmo onde possa escolher que tipo de média
deseja calcular a partir de três notas. Faça um programa que leia as
notas, a opção escolhida pelo usuário e calcule a média.

1. Aritmética;
2. Ponderada (Pesos: 3, 3, 4);
3. Harmônica (fórmula a seguir)
   #+begin_example
   3 / (1/a) + (1/a) + (1/a)
   #+end_example

#+begin_src C :tangle lista02_tipo_de_media.c
#include <stdio.h>

int main() {
    
    //Variáveis de entrada
    int tipo;
    float n1, n2, n3, media;
    //Variáveis auxiliares 
    int lidos;

    //Entrada de dados
    printf("Entre com o tipo de media\n1.Aritmetica\n2.Ponderada (pesos 3, 3, 4)\n3.Harmonica\n");
    lidos = scanf("%d", &tipo);
    if (lidos != 1) {
        printf("Houve um erro na leitura!\n");
        return 1;
    }

    if (tipo < 1 || tipo > 3) {
        printf("Tipo inválido!\n");
        return 1;
    }

    printf("Entre com as 3 notas: ");
    lidos = scanf("%f %f %f", &n1, &n2, &n3);
    if (lidos != 3) {
        printf("Houve um erro na leitura!\n");
        return 1;
    }

    //Processamento e saída de dados
    if (tipo == 1) {
        media = (n1 + n2 + n3) / 3;
        printf("A media aritmetica ficou em %.1f\n", media);
    } else if (tipo == 2) {
        media = (3 * n1 + 3 * n2 + 4 * n3) / 10;
        printf("A media ponderada 3 3 4 ficou em %.1f\n", media);
    } else {
        media = 3 / (1 / n1 + 1 / n2 + 1 / n3);
        printf("A media harmonica fechou em %.1f\n", media);
    }

    return 0;
}

#+end_src

* Calculo de prêmio

Faça um programa que lê o número de um vendedor, seu salário fixo e o
total de vendas por ele efetuadas no mês. Acrescentar ao salário um
prêmio, conforme a seguinte tabela:

| Total de vendas no mês (V) | Prêmio |
|----------------------------+--------|
| 100 < V <= 500             |     50 |
| 500 < V <= 750             |     70 |
| 750 < V                    | 100    |

#+begin_src C :tangle lista02_calculo_de_premio.c
#include <stdio.h>

int main() {
    
    //Variáveis de entrada
    int id, vendas;
    float salario;
    //Variáveis auxiliares 
    int lidos;

    //Entrada de dados
    printf("Entre com o id do vendedor: ");
    lidos = scanf("%d", &id);
    if (lidos != 1) {
        printf("Houve um erro na leitura!\n");
        return 1;
    }

    printf("Entre com o total de vendas e o salario, repectivamente: ");
    lidos = scanf("%d %f", &vendas, &salario);
    if (lidos != 2) {
        printf("Houve um erro na leitura!\n");
        return 1;
    }

    //Processamento e saída de dados
    if (100 < vendas && vendas <= 500) salario += 50;
    else if (500 < vendas && vendas <= 750) salario += 70;
    else if (750 < vendas) salario += 100;

    printf("O salario final do vendedor eh de R$%.2f\n", salario);

    return 0;
}

#+end_src 

* Pares e ímpares

Faça um programa que lê 3 números e que informa quantos desses números
são ou pares e positivos ou ímpares e negativos. Por exemplo, entre os
números 1, 2, -3, 4, 5, -6, -7, e 8, temos 5 números que satisfazem os
critérios.

#+begin_src C :tangle lista02_pares_e_impares.c
#include <stdio.h>

int main() {
    
    //Variáveis de entrada
    int a, b, c, validos = 0;
    //Variáveis auxiliares 
    int lidos;

    //Entrada de dados
    printf("Entre com os 3 numeros: ");
    lidos = scanf("%d %d %d", &a, &b, &c);
    if (lidos != 3) {
        printf("Houve um erro na leitura!\n");
        return 1;
    }

    //Processamento e saída de dados
    if ((a < 0 && a % 2 == -1) || (a > 0 && a % 2 == 0)) validos++;
    if ((b < 0 && b % 2 == -1) || (b > 0 && b % 2 == 0)) validos++;
    if ((c < 0 && c % 2 == -1) || (c > 0 && c % 2 == 0)) validos++;
    
    printf("A quantidade de numeros que validam os criterios eh %d\n", validos);


    return 0;
}

#+end_src

* Conceder aumento

Uma empresa possui 3 funcionários. Esta empresa resolveu conceder
aumento para os funcionários que possuem mais de 2 dependentes e que
ganham menos que um determinado valor de referência. Faça um programa
para auxiliar esta empresa a processar essas informações. O programa
deve inicialmente ler o valor de referência. A seguir, o programa deve
ler as seguintes informações de cada um dos 3 funcionários: código
(numérico), número de dependentes e salário atual. O programa deve
informar os códigos dos funcionários que ganharão aumento. Além disso,
ao fim do programa, ele deve informar a quantidade de funcionários que
ganharão aumento.

#+begin_src C :tangle lista02_conceder_aumento.c
#include <stdio.h>

int main() {
    
    //Variáveis de entrada
    int id1, id2, id3, dep1, dep2, dep3, aumento = 0;
    float ref, s1, s2, s3;
    //Variáveis auxiliares 
    int lidos;

    //Entrada de dados
    printf("Entre com o valor de referencia: ");
    lidos = scanf("%f", &ref);
    if (lidos != 1) {
        printf("Houve um erro na leitura!\n");
        return 1;
    }

    //Funcionario 1
    printf("Insira o id, numero de dependentes e salário do funcionario 1: ");
    lidos = scanf("%d %d %f", &id1, &dep1, &s1);
    if (lidos != 3) {
        printf("Houve erro na leitura!\n");
        return 1;
    }

    //Funcionario 2
    printf("Insira o id, numero de dependentes e salário do funcionario 2: ");
    lidos = scanf("%d %d %f", &id2, &dep2, &s2);
    if (lidos != 3) {
        printf("Houve erro na leitura!\n");
        return 1;
    }

    //Funcionario 3
    printf("Insira o id, numero de dependentes e salário do funcionario 3: ");
    lidos = scanf("%d %d %f", &id3, &dep3, &s3);
    if (lidos != 3) {
        printf("Houve erro na leitura!\n");
        return 1;
    }



    //Processamento e saída de dados
    if (dep1 > 2 || s1 < ref) {
        printf("Funcionario 1 recebera aumento!\n");
        aumento++;
    }
    if (dep2 > 2 || s2 < ref) {
        printf("Funcionario 2 recebera aumento!\n");
        aumento++;
    }
    if (dep3 > 2 || s3 < ref) {
        printf("Funcionario 3 recebera aumento!\n");
        aumento++;
    }

    printf("No total foram %d aumentos!\n", aumento);

    return 0;
}

#+end_src

* Processa entrevista

Faça um programa para auxiliar o IBGE a processar dados de uma
entrevista. O programa deve inicialmente ler a idade de uma pessoa. Se
esta pessoa tiver idade inferior a 18 anos, o programa deve finalizar,
informando que a pessoa é menor de idade. Caso a idade seja superior a
16 anos, o programa deve perguntar se esta pessoa trabalha. A resposta
deve ser lida como um caractere (S para sim e N para Não). Caso a
pessoa trabalhe, o programa deve ler o salário mensal da pessoa e o
número de horas que ela trabalha por mês e deve informar quanto esta
pessoa ganha por hora trabalhada. Caso a pessoa não trabalha o
programa deve finalizar, informando que a pessoa não trabalha.