# -*- coding: utf-8 -*-
# -*- mode: org -*-
#+startup: beamer overview indent
#+LANGUAGE: pt-br
#+TAGS: noexport(n)
#+EXPORT_EXCLUDE_TAGS: noexport
#+EXPORT_SELECT_TAGS: export

#+Title: Algoritmos
#+Subtitle: *INF01202*
#+Author: Prof. Lucas Mello Schnorr
#+Date: \copyleft

#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [xcolor=dvipsnames]
#+OPTIONS: title:nil H:1 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+LATEX_HEADER: \input{org-babel.tex}

#+latex: \newcommand{\mytitle}{Apresentação \linebreak Algoritmos e Programação}
#+latex: \mytitleslide

* Os professores

Prof. Lucas M. Schnorr \hfill \to aulas téoricas
+ schnorr@inf.ufrgs.br

#+latex: \vfill

Profa. Brenda Salenave Santana \hfill \to práticas I
+ brendasalenave@live.com

Prof. Gabriel Ammes Pinho \hfill \to práticas J
+ gapinho@inf.ufrgs.br
     
* Motivação

#+BEGIN_CENTER
Por que fazer INF01202?

Algoritmos e Programação
#+END_CENTER

* Motivação \to Adquirir *Pensamento Computacional*

Pensamento Computacional -- /Computational Thinking/
- Habilidades e limites da computação
- Mapear problemas em ``algo computacional''
- Pensar como cientistas da computação

* Objetivo Geral

#+begin_center
Introduzir o uso do computador na solução de problemas,

através da construção de programas
#+end_center

* O que vamos fazer na disciplina?

1. Análise do problema
2. Escolha de uma solução para resolver o problema (às vezes temos
   mais de uma possibilidade)
3. Construção do algoritmo que implementa a solução do problema
4. Escrever o algoritmo numa linguagem de programação
5. Teste/Execução do programa

* Funcionamento das aulas

A presença será aferida (75% de frequência evita FF)
- São 45 encontros no total, portanto 12 faltas implica em FF

#+latex: \vfill

Realizar exercícios propostos em aula prática

#+latex: \vfill

Perguntar sempre em caso de dúvida
- seja ator do teu aprendizado

* Abono de frequência por razões de saúde

#+latex: \scalebox{0.8}{\vbox{
Recuperação de frequência ou atividades avaliativas por licença médica.

Os casos de licença médica do aluno ou para atendimento de familiar
que afetem atividades avaliativas devem ser encaminhados ao
Departamento de Atenção a Saúde da UFRGS seguindo orientações deste
link: https://www.ufrgs.br/das/pericia-oficial-em-saude-alunos/

Para solicitar a Licença para Tratamento de Saúde, o aluno deve
encaminhar a documentação médica (atestado original ou cópia
autenticada com o CID -- Codigo Internacional de Doenças) para o
e-mail: atestadosalunos@ufrgs.br e solicitar avaliação. O documento
será analisado e os atestados médicos/odontológicos que solicitarem
até cinco dias corridos de afastamento (computados fins de semana e
feriados) poderão ser registrados com dispensa de perícia.

No corpo do e-mail em que foi enviado o atestado, devem constar
informados os seguintes dados: nome completo, número do cartão UFRGS,
curso, telefone para contato.

Caso haja necessidade de agendamento de perícia, você será informado,
através do seu e-mail, da data e do horário de comparecimento ao
Departamento de Atenção à Saúde para a realização do exame pericial. O
DAS envia ao professor o período do afastamento, sem compartilhar
nenhuma informação pessoal do estudante.

IMPORTANTE: Aulas abonadas não constam como presença; O estudante deve
combinar com o professor a recuperação das atividades avaliativas.
#+latex: }}

* Plano, cronograma, bibliografia, projeto

+ Súmula, conteúdo programático, bibliografia e cronograma
+ Procedimentos didáticos, laboratórios
+ Trabalhos, provas e avaliação
  
#+BEGIN_CENTER
Consulte no Portal do Aluno da UFRGS, ou uma cópia no moodle
#+END_CENTER

#+latex: \vfill

Vamos revisar os pontos juntos!

* Bibliografia (Geral)

#+latex: \cortesia{../../../Algoritmos/Edison/Teoricas/aula01_completa_slide_13.pdf}{Prof. Edison Pignaton de Freitas}

* Bibliografia (Específica da Linguagem C)

#+latex: \cortesia{../../../Algoritmos/Edison/Teoricas/aula01_completa_slide_20.pdf}{Prof. Edison Pignaton de Freitas}

* Avaliação

*Duas provas* (P1 e P2)
- Testará os aspectos teóricos da disciplina
- As provas englobam os assuntos vistos até então

*Exercícios Práticos* (AP)
- Realizados nas aulas práticas

*Trabalho Final* (TF)
- Respeito das especificações, linguagem C
- Testes

#+latex: \vfill\pause

#+BEGIN_CENTER
Nota final

P1 \times 0.30 + P2 \times 0.45 + AP \times 0.15 + TF \times 0.10
#+END_CENTER

#+latex: \pause

#+BEGIN_CENTER
Mapeamento para conceito

8.5 -- 10 \to A

7.5 -- 8.4 \to B

6.0 -- 7.4 \to C

0.0 -- 5.9 \to D
#+END_CENTER
* Recuperação

Se o aluno não atingir nota 6,0 na Média Final, poderá realizar uma
prova de recuperação sobre toda a matéria. Se a média entre a prova de
recuperação e a nota final da disciplina for maior ou igual a 6,0, o
aluno será aprovado com C.

#+BEGIN_CENTER
(Media Final \times 0.4 + Prova Recuperação \times 0.6) >= 6,0 \to Conceito C
#+END_CENTER

A apresentação do Trabalho Final, mesmo que não execute perfeitamente,
é pré-requisito para a realização da recuperação.

* Algoritmo para avaliação

Normal
#+begin_src C
Se Frequência < 75%
   Conceito FF
Senão Se Média >= 8,5
   Conceito A
Senão Se Média >= 7,5
   Conceito B
Senão Se Média >= 6,0
   Conceito C
Senão
   Recuperação
#+end_src

#+latex: \pause

Recuperação
#+begin_src C
Se Média < 6,0 e Trabalho diferente de 0,0 e Frequência >= 75%
   Prova Recuperação (Toda a Matéria)
   Final = (Média Final * 0.4 + Recuperação * 0.6)

Se Final >= 6,0
   Conceito C
Senão
   Conceito D
#+end_src

* Ferramenta EAD

#+BEGIN_CENTER
Aulas Teóricas e Práticas:

Moodle da UFRGS
#+END_CENTER

#+latex: \vfill

Em dúvidas
- Seja ator do teu aprendizado
- Discuta com os colegas
- Converse com o monitor
- Converse com os professores

* Cronograma

Verifique Moodle

#+latex: \bigskip

Vamos revisá-lo juntos.
