# -*- coding: utf-8 -*-
# -*- mode: org -*-
#+startup: beamer overview indent
#+LANGUAGE: pt-br
#+TAGS: noexport(n)
#+EXPORT_EXCLUDE_TAGS: noexport
#+EXPORT_SELECT_TAGS: export

#+Title: Algoritmos
#+Subtitle: *INF01202*
#+Author: Prof. Lucas Mello Schnorr
#+Date: \copyleft

#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [xcolor=dvipsnames]
#+OPTIONS: title:nil H:1 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+LATEX_HEADER: \input{org-babel.tex}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{systeme}

#+latex: \newcommand{\mytitle}{Arquivos}
#+latex: \mytitleslide

* Sumário
Lidar com Arquivos
- Introdução
- Conceitos
- Terminologia

#+latex: \vfill

Em C (lidar com o conteúdo de arquivos)
- Abrir ~fopen~
- Fechar ~fclose~
- Ler ~fread~
- Escrever ~fwrite~
- Descarregar ~fflush~
- Testar fim de arquivo ~feof~
- Avaliar condição de erro ~ferror~

* Arquivos e Streams

*Arquivo*: uma sequência de bytes registradas de maneira permanente
- Permitem /perenizar/ informações de um programa
Arquivos são armazenados em memória auxiliar
- Discos (rígidos, sólidos), /Pendrive/, Cartões SD, Fita
A alteração de um arquivo é permanente

Arquivos podem ser bem grandes!

#+latex: \vfill\pause

*Stream*: uma interface de E/S no sistema operacional
- Um canal de manipulação que pode representar vários dispositivos
  - Um arquivo (no disco HDD, por exemplo)
  - O teclado (/stdin/)
  - A tela (/stdout/)
- Simplifica a programação
  - Muda o suporte (SSD, HDD, Fita), mesma forma de acessar
- Dados e operações são em geral ``bufferizadas''

* Tipos de Arquivo

*Binário*
- Uma sequência de bytes que não pode ser interpretada em ASCII
- Em geral, um padrão de bits tal qual aparece na memória principal
  #+attr_latex: :options fontsize=\tiny
  #+begin_src C
  #include <stdio.h>
  float f;
  f = -1298721.72672;
  FILE *fp = fopen("arquivo.bin", "w");
  fwrite(&f, sizeof(float), 1, fp);
  #+end_src

  #+RESULTS:

  #+attr_latex: :options fontsize=\tiny
  #+begin_src shell :results output :exports results
  wc -c arquivo.bin
  xxd -l 4 -b arquivo.bin
  #+end_src

  #+RESULTS:
  : 4 arquivo.bin
  : 00000000: 00001110 10001001 10011110 11001001                    ....
  Mais informações sobre codificação =float=: \\
  https://en.wikipedia.org/wiki/IEEE_754

#+latex: \pause\vfill

*Texto*
- Uma sequência de bytes interpretável em ASCII
- Podemos abrir com um editor de texto puro

* Arquivo Binário

Uma sequência de bytes que não pode ser interpretada em ASCII
- Dados simples
- Dados estruturados
Tamanho do arquivo é a quantidade de bytes registradas no arquivo
- Os elementos não tem nome
- ``Formato binário''
O acesso pode ser sequencial ou fora de ordem
- Analogia da ``agulha de leitura''

#+latex: \vfill\pause

Representação gráfica de um arquivo de 16 bytes 

(o conteúdo do arquivo são as quatro caixas brancas)
| / |            | <> | > | > |  > |
|   | Endereço \to |  0 | 4 | 8 | 12 |
|---+------------+----+---+---+----|
|   | Conteúdo \to |    |   |   |    |
|---+------------+----+---+---+----|
(as separações entre bytes são apenas ilustrativas)

* Operações em C para arquivos binários
#+BEGIN_CENTER
Retiradas da biblioteca ~stdio.h~
#+END_CENTER

| *Operação*                 | *Função* |
|--------------------------+--------|
| Abrir                    | ~fopen~  |
| Fechar                   | ~fclose~ |
| Ler                      | ~fread~  |
| Escrever                 | ~fwrite~ |
| Descarregar              | ~fflush~ |
| Testar fim de arquivo    | ~feof~   |
| Avaliar condição de erro | ~ferror~ |

* Protótipos das funções

#+begin_center
O que há de comum entre estas funções?
#+end_center

#+latex: \vfill

#+attr_latex: :options fontsize=\normalsize
#+BEGIN_SRC C
FILE *fopen(const char *pathname, const char *mode);

int fclose(FILE *stream);

size_t fread(void *ptr, size_t size, size_t nmemb, FILE *stream);

size_t fwrite(const void *ptr, size_t size, size_t nmemb, FILE *stream);

int fflush(FILE *stream);

int feof(FILE *stream);

int ferror(FILE *stream);
#+END_SRC

#+latex: \pause

Um envolvimento com um ponteiro para uma estrutura =FILE=.

* O ponteiro para uma estrutura ~FILE~ (/aka/ ~FILE*~)

O tipo =FILE= representa uma /stream/
- Deve ser sempre declarada como ponteiro
- É uma estrutura que tem dados para controle do fluxo
  #+begin_src C
  #include <stdio.h>
  FILE *fp;
  #+end_src
- Cada arquivo aberto deve ter sua variável =FILE*=

#+latex: \vfill\pause

Um exemplo com a possibilidade para trabalhar com três arquivos
#+attr_latex: :options fontsize=\large
#+begin_src C
#include <stdio.h>
int main() {
  FILE *arq0 = NULL, *arq1 = NULL, *arq2 = NULL;
  // operações com arquivos
  return 0;
}
#+end_src

* Sempre verificar o retorno destas funções

#+begin_center
fopen, fclose, fread, fwrite, fflush, feof, ferror

O sucesso ou fracasso da execução destas funções

pode ser verificado a partir do valor retornado.
#+end_center

Especialmente importante para =fopen=, =fread=, =fwrite=.

#+attr_latex: :options fontsize=\large
#+begin_src C
#include <stdio.h>
int main() {
  FILE *arq = fopen("arquivo.bin", "r");
  if (arq == NULL) {
    // A abertura do arquivo falhou
  }else{
    // O arquivo foi aberto com sucesso
  }
  // operações com arq
  return 0;
}
#+end_src

* Abrir arquivo ~fopen~

#+attr_latex: :options fontsize=\normalsize
#+BEGIN_SRC C
FILE *fopen(const char *pathname, const char *mode);
#+END_SRC

~pathname~ é o ``caminho'' para o arquivo (o nome do arquivo)

~mode~ é o modo de abertura
| *Modo* | *Comportamento*                                   | ~stream~ |
|------+-------------------------------------------------+--------|
| r    | para leitura                                    | início |
| r+   | para leitura e escrita, não apaga arquivo       | início |
| w    | para escrita, apaga arquivo se existe           | início |
| w+   | para leitura e escrita, o arquivo é truncado    | início |
| a    | para concatenação no final do arquivo           | fim    |
| a+   | para leitura e concatenação no final do arquivo | fim    |

#+latex: \pause

Pode-se misturar modos.

Outros modos relevantes: ~b~ para arquivos binários \\
(especialmente para ambientes não-UNIX)

#+latex: \pause

Valor de retorno:
- se tudo bem, ponteiro para o descrito de arquivo subjacente
- caso contrário, ~NULL~

* Fechar arquivo ~fclose~

Protótipo
#+attr_latex: :options fontsize=\normalsize
#+BEGIN_SRC C
int fclose(FILE *stream);
#+END_SRC

A função ~fclose~ descarrega o stream apontado por ~stream~ (escrevendo
qualquer dado buferizado usando ~fflush~) e fecha o descritor de arquivo
subjacente.

Valor de retorno
- se tudo bem, 0 é retornado
- caso contrário, o valor de ~EOF~ é retornado.

* Exemplo com fopen/fclose

#+attr_latex: :options fontsize=\normalsize
#+BEGIN_SRC C
#include <stdio.h>
int main() {
  FILE *arquivo;
  arquivo = fopen("notas_da_turma.bin", "r");
  if (arquivo == NULL){
    printf("O arquivo não pode ser aberto.\n");
  }
  return 0;
}
#+END_SRC

#+latex: \pause

Assumindo que o arquivo existe, o que aconteceria se:
- O modo fosse "rb"
- O modo fosse "ra"
- O modo fosse "a"
- O modo fosse "w"

* A função de descarregamento ~fflush~

Para /streams/ de saída
- Força a escrita em disco de todos os dados em /buffer/

#+latex: \pause

Para /streams/ de entrada
- Desconsidera todos os dados em /buffer/ que ainda não consumidos

#+latex: \vfill\pause

Para o caso do exemplo abaixo
#+BEGIN_SRC C
fflush(NULL);
#+END_SRC
a função descarrega _todos_ os /streams/ de saída abertos.

* Escrever ~fwrite~

Protótipo
#+attr_latex: :options fontsize=\normalsize
#+BEGIN_SRC C
size_t fwrite(const void *ptr,
	      size_t size,
	      size_t nmemb,
	      FILE *stream);
#+END_SRC

Escreve ~nmemb~ itens de dados, cada um de tamanho ~size~ bytes, para o
stream apontado por ~stream~, obtendo os dados da localização dada pelo
endereço _em_ ~ptr~.

#+latex: \pause\vfill

Exemplos
#+attr_latex: :options fontsize=\normalsize
#+BEGIN_SRC C
int meu_inteiro;
fwrite(&meu_inteiro, sizeof(int), 1, arquivo);

double muitos_dados[TAMANHO];
fwrite(&muitos_dados, sizeof(double), TAMANHO, arquivo);
#+END_SRC

* Ler ~fread~

Protótipo
#+attr_latex: :options fontsize=\normalsize
#+BEGIN_SRC C
size_t fread(void *ptr,
	     size_t size,
	     size_t nmemb,
	     FILE *stream);
#+END_SRC

Lê ~nmemb~ itens de dados, cada um de tamanho ~size~ bytes, do stream
apontado por ~stream~, registrando os dados lidos na localização dada
pelo endereço _em_ ~ptr~.

#+latex: \pause\vfill

Exemplos
#+attr_latex: :options fontsize=\normalsize
#+BEGIN_SRC C
int meu_inteiro;
fread(&meu_inteiro, sizeof(int), 1, arquivo);

double muitos_dados[TAMANHO];
fread(&muitos_dados, sizeof(double), TAMANHO, arquivo);
#+END_SRC
* Valor de retorno de ~fwrite~ e ~fread~

Protótipos
#+attr_latex: :options fontsize=\normalsize
#+BEGIN_SRC C
size_t fwrite(const void *ptr,
	      size_t size,
	      size_t nmemb,
	      FILE *stream);
size_t fread(void *ptr,
	     size_t size,
	     size_t nmemb,
	     FILE *stream);
#+END_SRC

#+BEGIN_CENTER
As duas funções retornam a quantidade de

elementos efetivamente escritos ou lidos.
#+END_CENTER

* Testar ~EOF~ com ~feof~ e condição de erro com ~fwrite~

#+attr_latex: :options fontsize=\normalsize
#+BEGIN_SRC C
int feof(FILE *stream);
int ferror(FILE *stream);
#+END_SRC

A função ~feof~ testa o indicador de ``fim de arquivo'' para o stream
apontado por ~stream~, retornando não zero se estiver setado.

A função ~ferror~ testa o indicador de erro para o stream apontado por
~stream~, retornando não zero se estiver setado.

#+latex: \pause

#+BEGIN_CENTER
Estas funções podem (ou até devem) ser empregadas

após cada operação de entrada/saída.
#+END_CENTER

#+latex: \pause

Exemplo: ler enquanto não chegar no fim do arquivo
#+BEGIN_SRC C
while(!feof(arquivo)) { ... }
#+END_SRC

Exemplo: verificar se houveram erros na leitura
#+BEGIN_SRC C
int meu_inteiro;
fread(&meu_inteiro, sizeof(int), 1, arquivo);
if (ferror(arquivo)) {
  // aconteceu um erro na leitura
}
#+END_SRC

* Exercício #1

Faça quatro programas (cada programa no seu arquivo):

1. Um programa que grava um arquivo composto por =atleta_t=
   #+begin_src C
   #define TAM 100
   typedef struct {
     char nome[TAM];
     int idade;
     float altura;
   } atleta_t;
   #+end_src

2. Um programa que lista os atletas de um arquivo

3. Um programa com uma função auxiliar que recebe um nome de um atleta
   e que em seguida procura este nome no arquivo informado para
   informar sua idade e altura. Sugestão de protótipo
   #+begin_src C
   void procura_atleta(FILE *arq, char *nome);
   #+end_src

4. Um programa para inserir um novo atleta no final do arquivo


