# -*- coding: utf-8 -*-
# -*- mode: org -*-
#+startup: beamer overview indent
#+LANGUAGE: pt-br
#+TAGS: noexport(n)
#+EXPORT_EXCLUDE_TAGS: noexport
#+EXPORT_SELECT_TAGS: export

#+Title: Algoritmos
#+Subtitle: *INF01202*
#+Author: Prof. Lucas Mello Schnorr
#+Date: \copyleft

#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [xcolor=dvipsnames,10pt]
#+OPTIONS: title:nil H:1 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+LATEX_HEADER: \input{org-babel.tex}

#+latex: \newcommand{\mytitle}{Apresentação \linebreak Algoritmos e Programação}
#+latex: \mytitleslide

* O professor

Prof. Lucas M. Schnorr \hfill \to aulas téoricas
+ schnorr@inf.ufrgs.br

* Motivação

#+BEGIN_CENTER
Por que fazer INF01202?

Algoritmos e Programação
#+END_CENTER

* Motivação \to Adquirir *Pensamento Computacional*

2. Escolha de uma solução para resolver o problema
3. Construção do algoritmo que implementa a solução do problema
4. Escrever o algoritmo numa linguagem de programação
5. Teste/Execução do programa

* Funcionamento das aulas

A presença será aferida (75% de frequência evita FF)
- São +45+ 43 encontros no total, portanto +12+ 11 faltas implica em FF

#+latex: \vfill

Realizar exercícios propostos em aula prática

#+latex: \vfill

Perguntar sempre em caso de dúvida
- seja ator do teu aprendizado

* Abono de frequência por razões de saúde

#+latex: \scalebox{0.9}{\vbox{
Recuperação de frequência ou atividades avaliativas por licença médica.

Os casos de licença médica do aluno ou para atendimento de familiar
que afetem atividades avaliativas devem ser encaminhados ao
Departamento de Atenção a Saúde da UFRGS seguindo orientações deste
link: https://www.ufrgs.br/das/pericia-oficial-em-saude-alunos/

Para solicitar a Licença para Tratamento de Saúde, o aluno deve
encaminhar a documentação médica (atestado original ou cópia
autenticada com o CID -- Codigo Internacional de Doenças) para o
e-mail: atestadosalunos@ufrgs.br e solicitar avaliação. O documento
será analisado e os atestados médicos/odontológicos que solicitarem
até cinco dias corridos de afastamento (computados fins de semana e
feriados) poderão ser registrados com dispensa de perícia.

No corpo do e-mail em que foi enviado o atestado, devem constar
informados os seguintes dados: nome completo, número do cartão UFRGS,
curso, telefone para contato.

Caso haja necessidade de agendamento de perícia, você será informado,
através do seu e-mail, da data e do horário de comparecimento ao
Departamento de Atenção à Saúde para a realização do exame pericial. O
DAS envia ao professor o período do afastamento, sem compartilhar
nenhuma informação pessoal do estudante.

IMPORTANTE: Aulas abonadas não constam como presença; O estudante deve
combinar com o professor a recuperação das atividades avaliativas.
#+latex: }}

* Plano, cronograma, bibliografia, projeto

+ Súmula, conteúdo programático, bibliografia e cronograma
+ Procedimentos didáticos, laboratórios
+ Trabalhos, provas e avaliação

#+begin_center
Consulte no Portal do Aluno da UFRGS, ou uma cópia no moodle
#+end_center

#+latex: \vfill

Vamos revisar os pontos juntos!

* Bibliografia

Básica Essencial

1. Damas, Luis. Linguagem C. Rio de Janeiro: LTC, c2007. ISBN 9788521615194.
2. Salvetti, Dirceu Douglas; Barbosa, Lisbete Madsen. Algoritmos. Sao Paulo: Makron Books, c1998. ISBN 853460715X.

Básica

1. Deitel, Harvey M.. C How to Program. Estados Unidos: Prentice-Hall, 2007. ISBN 9780132404167.
2. Goodrich, Michael T.; Tamassia, Roberto. Projeto de algoritmos :fundamentos, análise e exemplos da internet. Porto Alegre: Bookman, 2004. ISBN 8536303034.
3. Harbison, Samuel P., III. Steele, Guy L., Jr.. C: manual de referência. Rio de Janeiro: Ciência Moderna, 2002. ISBN 8573932295.
4. Kernighan, Brian W.; Ritchie, Dennis M.. The C programming language. Englewood Cliffs: Prentice Hall, c1988. ISBN 0131103628.
5. Senne, Edson Luiz França. Curso de programação em C. São Paulo: Visual Books, 2009. ISBN 9788575022450.
6. Ziviani, N.. Projeto de Algoritmos Com Implementações em Pascal e C. THOMSON PIONEIRA, 2004. ISBN 8522103909.

* Avaliação

*Duas provas* (P1 e P2)
- Testará os aspectos teóricos da disciplina
- As provas englobam os assuntos vistos até então

*Exercícios Práticos* (AP)
- Realizados nas aulas práticas

*Trabalho Final* (TF)
- Respeito das especificações, linguagem C
- Testes

#+latex: \vfill\pause

#+BEGIN_CENTER
Nota final

P1 \times 0.30 + P2 \times 0.40 + AP \times 0.15 + TF \times 0.15
#+END_CENTER

#+latex: \pause

#+BEGIN_CENTER
Mapeamento para conceito

9.0 -- 10.0 \to A

7.5 -- 8.9 \to B

6.0 -- 7.4 \to C

0.0 -- 5.9 \to D
#+END_CENTER

* Recuperação

Se o aluno não atingir nota 6,0 na Média Final, poderá realizar uma
prova de recuperação sobre toda a matéria. O cálculo da nota final que
envolve o resultado da prova de recuperação é explicitado abaixo.

#+BEGIN_CENTER
(Media Final \times 0.4 + Prova Recuperação \times 0.6) >= 6,0 \to Conceito C
#+END_CENTER

* Algoritmo para avaliação

Normal
#+begin_src C
Se Frequência < 75%
   Conceito FF
Senão Se Média >= 9,0
   Conceito A
Senão Se Média >= 7,5
   Conceito B
Senão Se Média >= 6,0
   Conceito C
Senão
   Recuperação
#+end_src

#+latex: \pause

Recuperação
#+begin_src C
Se Média < 6,0 e Frequência >= 75%
   Prova Recuperação (Toda a Matéria)
   Final = (Média Final * 0.4 + Recuperação * 0.6)

Se Final >= 6,0
   Conceito C
Senão
   Conceito D
#+end_src

* Acompanhamento

#+BEGIN_CENTER
Aulas Teóricas e Práticas.

Moodle da UFRGS
#+END_CENTER

#+latex: \vfill

Em dúvidas
- Seja ator do teu aprendizado
- Discuta com os colegas
- Converse com o monitor
- Converse com os professores

* Cronograma

_Cronograma_

#+latex: \bigskip

Verifique Moodle

#+latex: \bigskip

Vamos revisá-lo juntos.
