# -*- coding: utf-8 -*-
# -*- mode: org -*-
#+startup: beamer overview indent
#+LANGUAGE: pt-br
#+TAGS: noexport(n)
#+EXPORT_EXCLUDE_TAGS: noexport
#+EXPORT_SELECT_TAGS: export

#+Title: Comando Condicional de Seleção \linebreak =if= e Expressões Lógicas
#+Subtitle: *INF01202*
#+Author: Prof. Lucas Mello Schnorr
#+Date: \copyleft

#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [xcolor=dvipsnames]
#+OPTIONS: title:nil H:1 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+LATEX_HEADER: \input{org-babel.tex}

#+latex: \newcommand{\mytitle}{Comando Condicional de Seleção linebreak =if= e Expressões Lógicas}
#+latex: \mytitleslide

* Sumário

- Expressões lógicas
  - Operadores lógicos
  - Precedência de operadores
  - Operadores relacionados
- Comando condicional =if=
  - Com um único comando
  - Com múltiplos comandos
- Exemplo

* Motivação

#+latex: \cortesia{../../../Algoritmos/Marcelo/aulas/aula04/aula04_slide_11.pdf}{Prof. Marcelo Walter}

* Expressões lógicas com operadores lógicos

#+latex: \cortesia{../../../Algoritmos/Mara/Teoricas/Aula04-If_else_slide_08.pdf}{Prof. Mara Abel}

* Operadores relacionais

#+latex: \cortesia{../../../Algoritmos/Mara/Teoricas/Aula04-If_else_slide_09.pdf}{Prof. Mara Abel}

* Exemplos do emprego de operadores relacionais

#+latex: \cortesia{../../../Algoritmos/Marcelo/aulas/aula04/aula04_slide_14.pdf}{Prof. Marcelo Walter}

* Mistura de operadores lógicos e relacionais

#+latex: \cortesia{../../../Algoritmos/Claudio/Teorica/Aula04-expressoes_e_if_slide_10.pdf}{Prof. Claudio Jung}

* Vejamos um exemplo prático

#+BEGIN_SRC C :tangle e/exemplo-logicos.c
/* Programa que calcula algumas expressões lógicas */
#include <stdio.h>
int main() {
  int a, b, c, d, valor;          //Entrada
  a = 1;
  b = 3;
  c = 5;
  d = 7;
  valor = 9;
  int e1, e2, e3, e4, e5, e6, e7; //Saída

  e1 = (a > b) || (c < d);
  e2 = valor > 10;
  e3 = !(a + c < b);
  e4 = (a == b);
  e5 = (a == b) && (a>=c);
  e6 = (a != b);
  e7 = !((a >= b) || (a+c));

  printf("Entradas: a=%d, b=%d, c=%d, d=%d, valor=%d\n",
	 a, b, c, d, valor);
  printf("Saídas: e1=%d, e2=%d, e3=%d, e4=%d, e5=%d, e6=%d, e7=%d\n",
	 e1, e2, e3, e4, e5, e6, e7);
  return 0;
}
#+END_SRC

* Cuidados com inspirações da matemática

#+latex: \cortesia{../../../Algoritmos/Claudio/Teorica/Aula04-expressoes_e_if_slide_11.pdf}{Prof. Claudio Jung}

* Outros exemplos de misturas lógicas

#+latex: \cortesia{../../../Algoritmos/Mara/Teoricas/Aula04-If_else_slide_12.pdf}{Prof. Mara Abel}

* Precedência de operadores lógicos com exemplo

#+latex: \cortesia{../../../Algoritmos/Mara/Teoricas/Aula04-If_else_slide_13.pdf}{Prof. Mara Abel}

* Testes com os exemplos

#+latex: \cortesia{../../../Algoritmos/Edison/Teoricas/aula04_slide_19.pdf}{Prof. Edison Pignaton de Freitas}

#+BEGIN_CENTER
Vejamos como fica em _formato de árvore_, com regras de precedência.
#+END_CENTER

* Motivação para comandos de seleção condicional

#+latex: \cortesia{../../../Algoritmos/Edison/Teoricas/aula04_slide_21.pdf}{Prof. Edison Pignaton de Freitas}

* Comandos de seleção condicional

#+latex: \cortesia{../../../Algoritmos/Edison/Teoricas/aula04_slide_22.pdf}{Prof. Edison Pignaton de Freitas}

* Comando =if= (condicional simples, com único comando)

#+latex: \cortesia{../../../Algoritmos/Mara/Teoricas/Aula04-If_else_slide_22.pdf}{Prof. Mara Abel}

* Exemplo #1

#+latex: \cortesia{../../../Algoritmos/Mara/Teoricas/Aula04-If_else_slide_23.pdf}{Prof. Mara Abel}

* Exemplo #2 (Enunciado e Algoritmo)

#+latex: \cortesia{../../../Algoritmos/Claudio/Teorica/Aula04-expressoes_e_if_slide_17.pdf}{Prof. Claudio Jung}

* Exemplo #2 (Enunciado e Algoritmo Completo)

#+latex: \cortesia{../../../Algoritmos/Claudio/Teorica/Aula04-expressoes_e_if_slide_18.pdf}{Prof. Claudio Jung}

* Exemplo #2 (Código em C)

#+BEGIN_SRC C :tangle e/exemplo-livros.c
/* processa uma venda e avisa caso se mais de 10
unidades vendidas foram vendidas */
#include<stdio.h>
int main(void)
{
  char codigo;
  int nro_livros;
  float apagar;
  printf("digite o codigo do produto e número de unidades:\n");
  scanf(" %c %d",&codigo, &nro_livros);
  if (codigo == 'a'|| codigo == 'A')
    apagar = nro_livros*10;
  if (codigo == 'b'|| codigo == 'B')
    apagar = nro_livros*20;
  if (codigo == 'c' || codigo == 'C')
    apagar = nro_livros*30;
  printf("o valor a pagar é de R$ %6.2f.\n",apagar);
  if (nro_livros > 10)
    printf("Foram vendidas mais de 10 unidades do tipo %c.\n", codigo);
  return 0;
}
#+END_SRC

#+begin_src shell :results output :dir e
gcc exemplo-livros.c -o exemplo-livros
#./exemplo-livros
#+end_src

#+RESULTS:

* Exemplo #3 (Enunciado)

#+latex: \cortesia{../../../Algoritmos/Mara/Teoricas/Aula04-If_else_slide_27.pdf}{Prof. Mara Abel}

* Exemplo #3 (Ententendo o Enunciado)

#+latex: \cortesia{../../../Algoritmos/Edison/Teoricas/aula04_slide_35.pdf}{Prof. Edison Pignaton de Freitas}

* Exemplo #3 (Pensamento Computacional \to Passos)

#+latex: \cortesia{../../../Algoritmos/Mara/Teoricas/Aula04-If_else_slide_29.pdf}{Prof. Mara Abel}

* Exemplo #3 (Algoritmo)

#+latex: \cortesia{../../../Algoritmos/Mara/Teoricas/Aula04-If_else_slide_30.pdf}{Prof. Mara Abel}

* Exemplo #3 (Código em C)

#+BEGIN_SRC C :tangle e/exemplo-coordenadas.c
/* Obtem coordenadas e informa localização */
#include <stdio.h>
int main() {
  float x, y; //Entrada
  printf("Coordenadas: x = ");
  scanf("%f", &x);
  printf("e y = ");
  scanf("%f", &y);
  if ( x == 0 && y == 0 )
    printf("\n Ponto na origem");
  if ( x > 0 && y > 0 )
    printf("\n Ponto no quadrante 1");
  if ( x < 0 && y > 0 )
    printf("\n Ponto no quadrante 2");
  if ( x < 0 && y < 0 )
    printf("\n Ponto no quadrante 3");
  if ( x > 0 && y < 0 )
    printf("\n Ponto no quadrante 4");
  if ( x == 0 && y != 0 )
    printf("\n Ponto no eixo dos y");
  if ( x != 0 && y == 0 )
    printf("\n Ponto no eixo dos x");
  printf("\n");
  return 0;
}
#+END_SRC

#+begin_src shell :results output :dir e
gcc exemplo-coordenadas.c -o exemplo-coordenadas
./exemplo-coordenadas
#+end_src

#+RESULTS:
: 
:  Coordenadas: x = e y = 
:  Ponto na origem
* Comando =if= (cond. composto, com múltiplos comandos)

#+latex: \cortesia{../../../Algoritmos/Edison/Teoricas/aula04_slide_33.pdf}{Prof. Edison Pignaton de Freitas}

* Exemplo #4 (Livros, com desconto)

#+latex: \cortesia{../../../Algoritmos/Mara/Teoricas/Aula04-If_else_slide_34.pdf}{Prof. Mara Abel}

* Exemplo #4 (Código em C)

#+BEGIN_SRC C :tangle e/exemplo-livros-desconto.c
/* processa uma venda e avisa caso se mais de 10
unidades vendidas foram vendidas */
#include<stdio.h>
int main(void)
{
  char codigo;
  int nro_livros;
  float apagar;
  printf("digite o codigo do produto e número de unidades:\n");
  scanf(" %c %d",&codigo, &nro_livros);
  if (codigo == 'a'|| codigo == 'A') {
    apagar = nro_livros*10;
    apagar = apagar * 0.90;
  }
  if (codigo == 'b'|| codigo == 'B')
    apagar = nro_livros*20;
  if (codigo == 'c' || codigo == 'C')
    apagar = nro_livros*30;
  printf("o valor a pagar é de R$ %6.2f.\n",apagar);
  if (nro_livros > 10)
    printf("Foram vendidas mais de 10 unidades do tipo %c.\n", codigo);
  return 0;
}
#+END_SRC


#+begin_src shell :results output :dir e
gcc exemplo-livros-desconto.c -o exemplo-livros-desconto
#./exemplo-livros-desconto
#+end_src

* Cuidados nos erros comuns

- Confundir atribuição com comparação igual
- Esquecer as chaves em comando condicional com múltiplos comandos
