REVISAO="revisao-aula-01.pdf \
	 revisao-aula-02.pdf \
	 revisao-aula-04.pdf \
	 revisao-aula-05.pdf \
	 revisao-aula-07.pdf \
	 revisao-aula-08.pdf \
	 revisao-aula-10.pdf \
	 revisao-aula-11.pdf \
	 revisao-aula-13.pdf \
	 revisao-aula-15.pdf \
	 revisao-aula-16.pdf \
	 revisao-aula-17.pdf \
	 revisao-aula-18.pdf \
	 revisao-aula-23.pdf \
	 revisao-aula-25.pdf \
	 revisao-aula-26.pdf \
	 revisao-aula-28.pdf \
	 revisao-aula-29.pdf \
	 revisao-aula-31.pdf \
	 revisao-aula-32.pdf \
	 revisao-aula-34.pdf \
	 revisao-aula-35.pdf \
	 revisao-aula-37.pdf \
	 revisao-aula-38.pdf \
	 revisao-aula-40.pdf \
	 comentarios-p1.pdf"
ORIGINA="apresentacao.pdf \
arranjos.pdf \
for.pdf \
if-else.pdf \
if.pdf \
introducao.pdf \
maisfor.pdf \
sequencial.pdf \
strings.pdf \
switch.pdf \
tipos.pdf \
while.pdf \
matriz.pdf \
maismatriz.pdf \
revisao-p1.pdf \
funcoes.pdf \
parametros.pdf \
referencias.pdf \
ponteiros.pdf \
passagem-matrizes.pdf \
ordenamento-bolha.pdf \
estruturas.pdf \
typedef.pdf \
arquivo.pdf \
aleatorio.pdf \
arq-texto.pdf \
arq-texto-p2.pdf \
recursividade.pdf \
estruturacao.pdf \
revisao-p2.pdf \
revisao-p2-corrigido.pdf"

PDFS="$REVISAO $ORIGINA"

COMMAND="rsync -rv --progress $PDFS html.inf.ufrgs.br:./public_html/inf1202/"
echo $COMMAND
eval $COMMAND
